default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: regulations_development

test:
  <<: *default
  database: regulations_test

production:
  <<: *default
  database: regulations_production
  username: <%= ENV.fetch("DATABASE_USERNAME", "regulations") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  url: <%= ENV.fetch("DATABASE_URL") %>
